# Generated by Django 4.1 on 2023-10-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_visit_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='os',
            new_name='ip',
        ),
    ]
