services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
    command: postgres -c max_connections=200

  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    command:
      sh -c "python manage.py migrate &&
      python -u manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build: 
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./:/usr/src/app
    links:
      - redis
    depends_on:
      - redis
      - database

    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./:/usr/src/app
    links:
      - redis
    depends_on:
      - redis
    ports: 
      - "5555:5555"
