services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
    command: postgres -c max_connections=200

  web-app:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    command:
      sh -c "python -u manage.py migrate &&
      python -u manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/var/www/docker-vue
      - /var/www/docker-vue/node_modules
    environment:
      - npm_config_unsafe_perm=true
    ports:
      - "8080:8080"

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build: 
      context: ./backend
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./backend:/usr/src/app
    links:
      - redis
    depends_on:
      - redis
      - database
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass

  celery-beat:
    build: 
      context: ./backend
    hostname: celery-beat
    container_name: celery-beat
    entrypoint: celery
    command: -A celery_app.app beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./backend:/usr/src/app
    links:
      - worker
      - redis
      - database
    depends_on:
      - worker
      - redis
      - database
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass

  flower:
    build:
      context: ./backend
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./backend:/usr/src/app
    links:
      - redis
      - worker
      - celery-beat
    depends_on:
      - redis
    ports: 
      - "5555:5555"
