services:
  database:
    image: postgres
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
    command: postgres -c max_connections=200

  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    command:
      sh -c "python -u manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database
