# Generated by Django 4.2.3 on 2023-07-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image_product_type_review_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
